import React from "react";
import styles from "../Projects/Project.module.css";
import { Link } from "react-router-dom"

const Project = () => {
  return (
    <div className={styles.project} id="projects">
      <h2 className={styles.heading}>Projects</h2>
      <div className={styles.projectcontainer}>
        <div className={styles.projectboundary}>
          <div className={styles.projectimg}>
            <img src="/spacex.jpg" alt="project" />
          </div>
          <div className={styles.projectdata}>
            <h3>Space X</h3>
            <p>
              A complete Responsive Website made using Bootstrap which gives
              information about Solar system, Stars, Planets and other space
              objects.
            </p>
          </div>
          <div className={styles.btn}>
          <a href="https://mr-ankitpandey.github.io/Space-X/" target="_blank"><button>Live View</button></a>
            <a href="https://github.com/Mr-Ankitpandey/Space-X" target="_blank"><button>Source Code</button></a>
          </div>
        </div>
        <div className={styles.projectboundary}>
          <div className={styles.projectimg}>
            <img src="/unitconverter.jpg" alt="project" />
          </div>
          <div className={styles.projectdata}>
            <h3>Unit Master</h3>
            <p>
              A Unit convereter with dark theme which provides unit converting options
              from one unit into another of some Quantities.
            </p>
          </div>
          <div className={styles.btn}>
          <a href="https://unit-master.netlify.app/" target="_blank"><button>Live View</button></a>
          <a href="https://github.com/Mr-Ankitpandey/Unit-Calculator" target="_blank"><button>Source Code</button></a>
          </div>
        </div>
        <div className={styles.projectboundary}>
          <div className={styles.projectimg}>
            <img src="/calculator.jpg" alt="project" />
          </div>
          <div className={styles.projectdata}>
            <h3>Calculator</h3>
            <p>
              A basic Calculator made in React.js with all operations provided by a normal mobile Calculator
            </p>
          </div>
          <div className={styles.btn}>
            <a href="https://calculator7101.netlify.app/" target="_blank"><button>Live View</button></a>
            <a href="" target="_blank"><button>Source Code</button></a>
          </div>
        </div>
        <div className={styles.projectboundary}>
          <div className={styles.projectimg}>
            <img src="/numbersimulator.jpg" alt="project" />
          </div>
          <div className={styles.projectdata}>
            <h3>Number Simulator</h3>
            <p>
              It is a simple number guessing game which provides 6 attempts to
              guess the random number generated by computer.
            </p>
          </div>
          <div className={styles.btn}>
            <a href="https://number-simulator.netlify.app/" target="_blank"><button>Live View</button></a>
            <a href="https://github.com/Mr-Ankitpandey/Number-Simulator" target="_blank"><button>Source Code</button></a>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Project;
